services:

  service-discovery:
    build: ./service-discovery
    container_name: service-discovery
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8083:8083"
    depends_on:
      - service-discovery

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - service-discovery

  social-media-frontend:
    build: ./social-media-frontend
    container_name: social-media-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway